//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityHomework01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public int comID { get; set; }
        public int cpuBrandID { get; set; }
        public int opeSysID { get; set; }
        public SizeRAM ramSize { get; set; }
        public SizeDISK diskSize { get; set; }
        public SizeSSD ssdSize { get; set; }
        public decimal price { get; set; }
    
        public virtual CPU CPU { get; set; }
        public virtual OperatingSystem OperatingSystem { get; set; }
    }
}
