//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityHomework01
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowComputer
    {
        public int comID { get; set; }
        public string cpuName { get; set; }
        public string osName { get; set; }
        public byte ramSize { get; set; }
        public byte diskSize { get; set; }
        public byte ssdSize { get; set; }
        public decimal price { get; set; }
    }
}
