//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityHomework01
{
    using System;
    
    public enum SizeSSD : byte
    {
        SSD128GB = 0,
        SSD190GB = 1,
        SSD240GB = 2,
        SSD256GB = 3,
        SSD512GB = 4,
        SSD1TB = 5,
        SSD2TB = 6
    }
}
