//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityHomework01
{
    using System;
    
    public enum SizeRAM : byte
    {
        RAM2GB = 0,
        RAM4GB = 1,
        RAM8GB = 2,
        RAM12GB = 3,
        RAM16GB = 4,
        RAM32GB = 5,
        RAM64GB = 6
    }
}
