//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityHomework01
{
    using System;
    
    public enum SizeDISK : byte
    {
        HDD512GB = 0,
        HDD1TB = 1,
        HDD2TB = 2,
        HDD4TB = 3,
        HDD8TB = 4
    }
}
