USE egeturan

CREATE TABLE Deneme2(
ID smallint,
Name nvarchar(50))

INSERT INTO Deneme VALUES (2,'B')

GRANT CREATE TABLE TO turan
REVOKE CREATE TABLE TO turan

GRANT UPDATE ON Deneme TO turan
REVOKE UPDATE ON Deneme TO turan

GRANT INSERT, UPDATE, DELETE TO turan

DENY INSERT, SELECT ON Deneme TO turan

CREATE ROLE ege;
GRANT INSERT,UPDATE,SELECT,DELETE ON egeturan.dbo.Deneme TO ege

CREATE LOGIN eray WITH PASSWORD = 'eray1234';
GRANT INSERT,UPDATE,SELECT,DELETE ON egeturan.dbo.Deneme TO ege
CREATE USER eray FOR LOGIN eray;

--CREATE LOGIN smart WITH PASSWORD = 'Paro123!'
--CREATE USER smart FOR LOGIN smart
--GRANT INSERT,SELECT TO smart
--DENY UPDATE,DELETE TO smart

