//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_Blog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.usrImg = "imgs/defaultuser.png";
            this.usrActive = true;
            this.usrRole = 1;
            this.Articles = new HashSet<Article>();
        }
    
        public int usrID { get; set; }
        public string usrFullName { get; set; }
        public string usrEmail { get; set; }
        public string usrPassword { get; set; }
        public System.DateTime usrBirthDay { get; set; }
        public System.DateTime usrRegistered { get; set; }
        public Nullable<System.DateTime> usrRemoved { get; set; }
        public string usrImg { get; set; }
        public bool usrActive { get; set; }
        public byte usrRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
    }
}
