//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_Blog
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListEntriesWithAuthorName
    {
        public int artID { get; set; }
        public int artAuthor { get; set; }
        public string autName { get; set; }
        public System.DateTime artDate { get; set; }
        public string artTitle { get; set; }
        public string artText { get; set; }
    }
}
